### PR TITLE
Pivotal's Diversity Data

### PR DESCRIPTION
**Pull request by laurentropeano**
Submitting Pivotal's Diversity data to OpenDiversityData.org

### CODE REVIEW

**Comment by laurentropeano** [comment]
Submitting Pivotal's Diversity Data

**Comment by hougs** [comment]
Did you intend to close this PR? I'm happy to merge it if you consent. If you would like to withdraw it, that is also fine.

**Comment by laurentropeano** [comment]
Hi Juliet
Thanks for your help. I am new to github so perhaps I submitted something
incorrectly. I would like to publish Pivotal's Diversity data using the
data that I provided.
Could you help with that?

Thanks,
Lauren

On Thu, Mar 24, 2016 at 1:13 PM, Juliet Hougland notifications@github.com
wrote:

> Did you intend to close this PR? I'm happy to merge it if you consent. If
> you would like to withdraw it, that is also fine.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/doubleunion/opendiversitydata/pull/86#issuecomment-200932337

## 

Lauren Tropeano
Director, People Operations & HR Chief of Staff
office: 508-769-0990
ltropeano@pivotal.io

Have an HR question... contact our HR team at askHR@pivotal.io!
askHR@pivotal.io

**Comment by hougs** [comment]
Absolutely. I believe you accidentally "closed" this pull request. Original submitters only do this if they don't want their changes added anymore. I figured it was just a mistake which is why I asked. I'm happy to merge this in.

**Comment by laurentropeano** [comment]
Oh perfect! Thank you so much for noticing and proactively emailing me!
Would you mind letting me know when this has been merged in and is all set.
I truly appreciate your help with this.

Thanks so much,
Lauren

On Thu, Mar 24, 2016 at 1:49 PM, Juliet Hougland notifications@github.com
wrote:

> Absolutely. I believe you accidentally "closed" this pull request.
> Original submitters only do this if they don't want their changes added
> anymore. I figured it was just a mistake which is why I asked. I'm happy to
> merge this in.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/doubleunion/opendiversitydata/pull/86#issuecomment-200946962

## 

Lauren Tropeano
Director, People Operations & HR Chief of Staff
office: 508-769-0990
ltropeano@pivotal.io

Have an HR question... contact our HR team at askHR@pivotal.io!
askHR@pivotal.io

**Comment by hougs** [comment]
Merged!

**Comment by laurentropeano** [comment]
Thank you!

On Mar 25, 2016, at 10:35 AM, Juliet Hougland notifications@github.com
wrote:

Closed #86 https://github.com/doubleunion/opendiversitydata/pull/86.

—
You are receiving this because you modified the open/close state.
Reply to this email directly or view it on GitHub
https://github.com/doubleunion/opendiversitydata/pull/86#event-603072250

**Pull request closed without merging**
